version: "3.9"

services:

  redis:
    image: redis:7-alpine
    container_name: books_platform_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: books_platform_web
    restart: unless-stopped
    ports:
      - "3000:3000"
    depends_on:
      - redis
    volumes:
      - .:/app

volumes:
  redis_data:
